export const DATA = [
  {
    id: 1,
    name: 'Alex',
    nrc: '9/ZYT(C)121211',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/alex.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 2,
    name: 'Sr Ki',
    nrc: '9/ZYT(C)121212',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/sr-ki.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 3,
    name: 'Sara',
    nrc: '9/ZYT(C)121213',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/sara.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 4,
    name: 'Jemima',
    nrc: '9/ZYT(C)121214',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/jemima.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 5,
    name: 'Lisa',
    nrc: '9/ZYT(C)121215',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/lisa.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 6,
    name: 'Thea',
    nrc: '9/ZYT(C)121216',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/thea.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 7,
    name: 'Nannie',
    nrc: '9/ZYT(C)121217',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/nannie.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 8,
    name: 'Russell',
    nrc: '9/ZYT(C)121218',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/russell.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 9,
    name: 'Fabian',
    nrc: '9/ZYT(C)121219',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/fabian.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 10,
    name: 'Fletcher',
    nrc: '9/ZYT(C)121220',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/fletcher.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 11,
    name: 'Muhammed',
    nrc: '9/ZYT(C)121221',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/muhammed.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 12,
    name: 'Owain',
    nrc: '9/ZYT(C)121222',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/owain.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 13,
    name: 'Howard',
    nrc: '9/ZYT(C)121223',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/howard.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 14,
    name: 'Faith',
    nrc: '9/ZYT(C)121224',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/faith.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 15,
    name: 'Zakariya',
    nrc: '9/ZYT(C)121225',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/zakariya.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 16,
    name: 'Angus',
    nrc: '9/ZYT(C)121226',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/angus.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 17,
    name: 'Homer',
    nrc: '9/ZYT(C)121227',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/homer.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 18,
    name: 'Alec',
    nrc: '9/ZYT(C)121228',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/alec.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 19,
    name: 'Albert',
    nrc: '9/ZYT(C)121229',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/albert.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
  {
    id: 20,
    name: 'Samuel',
    nrc: '9/ZYT(C)121230',
    location: 'Nay Pyi Taw',
    role: 'Front-end',
    photo: 'assets/People/samuel.jpg',
    nrcCard: 'assets/ID/id.jpg',
  },
];
